### ISSUE TITLE
Trouble running example (Sketch1.js)

### ISSUE THREAD

**Issue by ciaron** [haschdl/SuperMidiJS#1]
I'm trying to run the example code on Chrome (on Linux). I'm simply loaded the SuperMidi.html file in the browser. The problem I see in the console is that the javascript is being blocked:

Access to script at 'file:///home/ciaron/SuperMidiJS/src/SuperMidi.js' from origin 'null' has been blocked by CORS policy: The response is invalid.

I'm not too familiar with p5js, or Javascript development in general - am I going about this the right way? Should I be running a webserver locally instead?

**Comment by ciaron** [comment]
I managed to get this working (right after submitting this issue!) by running a local server ("python -m http.server") in the examples/ folder. I also needed to copy the src/ folder to examples/src for the .js files to be found. Feel free to close this unless I've still missed the proper way to run the examples.

I still get errors, but the LPD8 has been recognised.

**Comment by haschdl** [comment]
Hello Ciaron! I’m glad you got it to run at last. I have a pending commit, which I must push to the repo. are you working with it today? I can push it soon. It’s not perfect yet but at least it’s more flexible now.

**Comment by haschdl** [comment]
hello @ciaron ! closing the issue, please create new ones for improvements or other issues
